# -*- coding: utf-8 -*-
"""script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q44FmDIkYHw7vsYuVzLV5CF90XTTarCc
"""

import streamlit as st

st.title('Hello Wilders, welcome to my application!')